
name: Deploy to Heroku on merge
'on':
  push:
    branches:
      - main
    paths:
      - 'server/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'xenah-dev-portal'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
